--- 
log_file: log/mongrel.log
cwd: /archivos/siscco
log_file: /var/log/mongrel.log
port: "8000"
environment: production
group: www
user: mongrel
address: 127.0.0.1
pid_file: tmp/pids/mongrel.pid
servers: 6 
